name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Base Docker image
      run: cd base && docker build . --file Dockerfile --tag davefinster/theia:go-$(date +%s) 
