name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Build the Base Docker image
      run: cd base && docker build . --file Dockerfile --tag davefinster/theia:base && docker tag davefinster/theia:base gcr.io/cluster-171711/theia-base:latest && docker push gcr.io/cluster-171711/theia-base:latest
    - name: Build the Golang Docker image
      run: cd golang && docker build . --file Dockerfile --tag davefinster/theia:go && docker tag davefinster/theia:go gcr.io/cluster-171711/theia-go:latest && docker push gcr.io/cluster-171711/theia-go:latest
